package editor;


import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.tree.TreePath;

import data.Data;
import data.DataItem;
import java.awt.event.WindowEvent;
import javax.swing.*;
import mode.*;
import util.Settings;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Arrian
 */
public class Application extends javax.swing.JFrame {


    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        setFocusable(true);
        addKeyListener((Editor) editorPanel);
        addMouseWheelListener((Editor) editorPanel);

        MouseListener ml = new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                int selRow = itemTree.getRowForLocation(e.getX(), e.getY());
                TreePath selPath = itemTree.getPathForLocation(e.getX(), e.getY());
                if (selRow != -1) {
                    if (e.getClickCount() == 1) {
                        Object object = selPath.getLastPathComponent();
                        if (object instanceof DataItem) {
                            DataItem item = (DataItem) selPath.getLastPathComponent();
                            getEditor().setSelectedDataItem(item);
                            modeGroup.setSelected(modeAdd.getModel(), true);
//
//                            idText.setText(Integer.toString(item.getId()));
//                            nameText.setText(item.getName());
//                            imageText.setText(item.getResources().toString());
//                            typeCombo.setSelectedIndex(item.getType().ordinal());
                        }
                    } else if (e.getClickCount() == 2) {
                        Object object = selPath.getLastPathComponent();
                        if (object instanceof DataItem) {
                            DataItem item = (DataItem) selPath.getLastPathComponent();
                            DataDialog dialog = new DataDialog(Application.this, item);
                            dialog.setVisible(true);
                        }
                    }
                }
            }
        };
        itemTree.addMouseListener(ml);
        expandTree();
    }
    
    private Editor getEditor()
    {
        return (Editor) editorPanel;
    }
    
    public void expandTree() {
        for (int i = 0; i < itemTree.getRowCount(); i++) {
            itemTree.expandRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeGroup = new javax.swing.ButtonGroup();
        jMenuItem2 = new javax.swing.JMenuItem();
        dataPanel = new javax.swing.JPanel();
        itemTreePane = new javax.swing.JScrollPane();
        itemTree = new javax.swing.JTree();
        editorPanel = new Editor();
        tools = new javax.swing.JToolBar();
        newWorld = new javax.swing.JButton();
        newData = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        undo = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        modeSelect = new javax.swing.JToggleButton();
        modeAdd = new javax.swing.JToggleButton();
        modeMove = new javax.swing.JToggleButton();
        modeRotate = new javax.swing.JToggleButton();
        modeHand = new javax.swing.JToggleButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        showDebug = new javax.swing.JToggleButton();
        menu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        saveWorldMenuItem = new javax.swing.JMenuItem();
        saveWorldAsMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        saveDataMenuItem = new javax.swing.JMenuItem();
        saveDataAsMenuItem = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        deleteMenuItem = new javax.swing.JMenuItem();
        duplicateMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor");

        dataPanel.setLayout(new java.awt.BorderLayout());

        itemTreePane.setBorder(null);
        itemTreePane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        itemTreePane.setMaximumSize(new java.awt.Dimension(0, 0));

        itemTree.setModel(Data.load(new File(Settings.DEFAULT_RESOURCE_LOCATION + Settings.DEFAULT_DATA_FOLDER + Settings.DEFAULT_DATA_FILE)));
        itemTree.setToolTipText("");
        itemTree.setAutoscrolls(true);
        itemTree.setDragEnabled(true);
        itemTree.setEditable(true);
        itemTree.setMinimumSize(null);
        itemTree.setName("");
        itemTree.setRootVisible(false);
        itemTree.setShowsRootHandles(true);
        itemTreePane.setViewportView(itemTree);

        dataPanel.add(itemTreePane, java.awt.BorderLayout.CENTER);

        editorPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout editorPanelLayout = new javax.swing.GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        editorPanelLayout.setVerticalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tools.setFloatable(false);
        tools.setRollover(true);

        newWorld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/box--plus.png"))); // NOI18N
        newWorld.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        newWorld.setFocusable(false);
        newWorld.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newWorld.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newWorld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWorldActionPerformed(evt);
            }
        });
        tools.add(newWorld);

        newData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/database--plus.png"))); // NOI18N
        newData.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        newData.setFocusable(false);
        newData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDataActionPerformed(evt);
            }
        });
        tools.add(newData);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/disk-black.png"))); // NOI18N
        save.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        save.setFocusable(false);
        save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        tools.add(save);
        tools.add(jSeparator6);

        undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/arrow-curve-180-left.png"))); // NOI18N
        undo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        undo.setFocusable(false);
        undo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        undo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        tools.add(undo);

        redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/arrow-curve.png"))); // NOI18N
        redo.setToolTipText("");
        redo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        redo.setFocusable(false);
        redo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        redo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });
        tools.add(redo);
        tools.add(jSeparator7);

        modeGroup.add(modeSelect);
        modeSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cursor.png"))); // NOI18N
        modeSelect.setSelected(true);
        modeSelect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        modeSelect.setFocusable(false);
        modeSelect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modeSelect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modeSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeSelectActionPerformed(evt);
            }
        });
        tools.add(modeSelect);

        modeGroup.add(modeAdd);
        modeAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/plus.png"))); // NOI18N
        modeAdd.setFocusable(false);
        modeAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modeAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeAddActionPerformed(evt);
            }
        });
        tools.add(modeAdd);

        modeGroup.add(modeMove);
        modeMove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/arrow-move.png"))); // NOI18N
        modeMove.setFocusable(false);
        modeMove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modeMove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modeMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeMoveActionPerformed(evt);
            }
        });
        tools.add(modeMove);

        modeGroup.add(modeRotate);
        modeRotate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/layer-rotate.png"))); // NOI18N
        modeRotate.setFocusable(false);
        modeRotate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modeRotate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modeRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeRotateActionPerformed(evt);
            }
        });
        tools.add(modeRotate);

        modeGroup.add(modeHand);
        modeHand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/hand.png"))); // NOI18N
        modeHand.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        modeHand.setFocusable(false);
        modeHand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modeHand.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modeHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeHandActionPerformed(evt);
            }
        });
        tools.add(modeHand);
        tools.add(jSeparator5);

        showDebug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/grid.png"))); // NOI18N
        showDebug.setSelected(true);
        showDebug.setFocusable(false);
        showDebug.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showDebug.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        showDebug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDebugActionPerformed(evt);
            }
        });
        tools.add(showDebug);

        fileMenu.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setLabel("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);
        fileMenu.add(jSeparator1);

        saveWorldMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveWorldMenuItem.setText("Save World");
        saveWorldMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveWorldMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveWorldMenuItem);

        saveWorldAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveWorldAsMenuItem.setText("Save World As...");
        saveWorldAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveWorldAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveWorldAsMenuItem);
        fileMenu.add(jSeparator2);

        saveDataMenuItem.setText("Save Data");
        saveDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveDataMenuItem);

        saveDataAsMenuItem.setText("Save Data As...");
        saveDataAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveDataAsMenuItem);
        fileMenu.add(jSeparator8);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setLabel("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menu.add(fileMenu);

        editMenu.setText("Edit");

        undoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoMenuItem.setText("Undo");
        undoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(undoMenuItem);

        redoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        redoMenuItem.setText("Redo");
        redoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(redoMenuItem);
        editMenu.add(jSeparator3);

        deleteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        deleteMenuItem.setText("Delete");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        duplicateMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        duplicateMenuItem.setText("Duplicate");
        duplicateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicateMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(duplicateMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setText("Copy");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        pasteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pasteMenuItem.setText("Paste");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);

        menu.add(editMenu);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tools, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tools, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1057)/2, (screenSize.height-803)/2, 1057, 803);
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        JFileChooser openFile = new JFileChooser();
        int returnValue = openFile.showOpenDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION)
        {
            getEditor().load(openFile.getSelectedFile(), (Data) itemTree.getModel());
        }
        
        
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveWorldMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveWorldMenuItemActionPerformed

    }//GEN-LAST:event_saveWorldMenuItemActionPerformed

    private void saveWorldAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveWorldAsMenuItemActionPerformed
        JFileChooser saveFile = new JFileChooser();
        int returnValue = saveFile.showSaveDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION) {
            File file = saveFile.getSelectedFile();
            getEditor().save(file);//, (Data) itemTree.getModel());
        }
    }//GEN-LAST:event_saveWorldAsMenuItemActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        getEditor().clear();
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void undoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMenuItemActionPerformed
        getEditor().undo();
    }//GEN-LAST:event_undoMenuItemActionPerformed

    private void redoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoMenuItemActionPerformed
        getEditor().redo();
    }//GEN-LAST:event_redoMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        getEditor().delete();
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void duplicateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicateMenuItemActionPerformed
        getEditor().duplicate();
    }//GEN-LAST:event_duplicateMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        getEditor().copy();
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        getEditor().paste();
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void newWorldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWorldActionPerformed
        getEditor().clear();
    }//GEN-LAST:event_newWorldActionPerformed

    private void newDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDataActionPerformed
        
    }//GEN-LAST:event_newDataActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        getEditor().undo();
    }//GEN-LAST:event_undoActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        getEditor().redo();
    }//GEN-LAST:event_redoActionPerformed

    private void modeSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeSelectActionPerformed
        getEditor().setMode(new ModeSelect((Editor) editorPanel));
    }//GEN-LAST:event_modeSelectActionPerformed

    private void modeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeAddActionPerformed
        getEditor().setMode(new ModeAdd(getEditor(), getEditor().getSelectedDataItem()));
    }//GEN-LAST:event_modeAddActionPerformed

    private void modeMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeMoveActionPerformed
        getEditor().setMode(new ModeMove(getEditor()));
    }//GEN-LAST:event_modeMoveActionPerformed

    private void modeRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeRotateActionPerformed
        getEditor().setMode(new ModeRotate(getEditor()));
    }//GEN-LAST:event_modeRotateActionPerformed

    private void modeHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeHandActionPerformed
        getEditor().setMode(new ModeHand(getEditor()));
    }//GEN-LAST:event_modeHandActionPerformed

    private void showDebugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDebugActionPerformed
        AbstractButton abstractButton = (AbstractButton) evt.getSource();
        boolean selected = abstractButton.getModel().isSelected();
        getEditor().setShowDebug(selected);
    }//GEN-LAST:event_showDebugActionPerformed

    private void saveDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveDataMenuItemActionPerformed

    private void saveDataAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataAsMenuItemActionPerformed
        JFileChooser saveFile = new JFileChooser();
        int returnValue = saveFile.showSaveDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION) {
            File file = saveFile.getSelectedFile();
            Data.save((Data)itemTree.getModel(), file);
        }
    }//GEN-LAST:event_saveDataAsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
        } catch (ClassNotFoundException e) {
        } catch (InstantiationException e) {
        } catch (IllegalAccessException e) {
        }

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
			public void run() {
                new Application().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem duplicateMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JPanel editorPanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTree itemTree;
    private javax.swing.JScrollPane itemTreePane;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JMenuBar menu;
    private javax.swing.JToggleButton modeAdd;
    private javax.swing.ButtonGroup modeGroup;
    private javax.swing.JToggleButton modeHand;
    private javax.swing.JToggleButton modeMove;
    private javax.swing.JToggleButton modeRotate;
    private javax.swing.JToggleButton modeSelect;
    private javax.swing.JButton newData;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JButton newWorld;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JButton redo;
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JButton save;
    private javax.swing.JMenuItem saveDataAsMenuItem;
    private javax.swing.JMenuItem saveDataMenuItem;
    private javax.swing.JMenuItem saveWorldAsMenuItem;
    private javax.swing.JMenuItem saveWorldMenuItem;
    private javax.swing.JToggleButton showDebug;
    private javax.swing.JToolBar tools;
    private javax.swing.JButton undo;
    private javax.swing.JMenuItem undoMenuItem;
    // End of variables declaration//GEN-END:variables
}
