######################################### Static Lib

env = Environment(CPPPATH = ['.'],
	LIBPATH = [
	'../deps/polycode/Core/Dependencies/lib',
	'../deps/polycode/Core/lib',
	'../deps/polycode/Modules/lib',
	'../deps/polycode/Modules/Dependencies/lib',
	'/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m'
	],
	LIBS = [
	'libPolycore',
	'libPolycode2DPhysics',
	'libpng15',
	'libfreetype',
	'liblibogg',
	'liblibvorbis',
	'liblibvorbisfile',
	'liblua5.1',
	'libphysfs',
	'libz',
	'libPolycode2DPhysics',
	'libPolycode3DPhysics',
	'libPolycodeTUIO',
	'libPolycodeUI',
	'libBox2D',
	'python3.4m'
	],
	CXXFLAGS="-std=c++0x")


Repository('include')

Repository('/Users/arrian/Dev/polycode-dev/Core/Contents/Include')
Repository('/Users/arrian/Dev/polycode-dev/Modules/Contents/2DPhysics/Include')
Repository('/Users/arrian/Dev/polycode-dev/Modules/Contents/UI/Include')
Repository('/Users/arrian/Dev/polycode-dev/Dependencies/freetype/src/freetype/include')

Repository('/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/include/python3.4m')


env.Append(CPPFLAGS=['-Wall', '-g', '-mmacosx-version-min=10.9'])
staticLib = env.StaticLibrary(target = 'Game',
            source = Glob('src/*.cpp'))

# staticInstall = env.Install('../bin/', staticLib)
# env.Program('game',
            # Glob('src/*.cpp'))

