include_paths = [
	'.',
	'include',
	'../../include',
	'/Users/arrian/Dev/polycode-dev/Core/Contents/Include',
	'/Users/arrian/Dev/polycode-dev/Modules/Contents/2DPhysics/Include',
	'/Users/arrian/Dev/polycode-dev/Modules/Contents/UI/Include',
	'/Users/arrian/Dev/polycode-dev/Dependencies/freetype/src/freetype/include',
	'/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/include/python3.4m',
	'/usr/local/Cellar/boost/1.56.0/include'
	]

lib_paths = [
	'.',
	'/Users/arrian/Dev/2d-engine/deps/polycode/Modules/lib',
	'/Users/arrian/Dev/2d-engine/deps/polycode/Modules/Dependencies/lib',
	'/usr/local/Cellar/boost/1.56.0/lib',
	'/usr/local/Cellar/boost-python/1.56.0/lib',
	'../deps/polycode/Core/Dependencies/lib',
	'../deps/polycode/Core/lib',
	'../deps/polycode/Modules/lib',
	'../deps/polycode/Modules/Dependencies/lib',
	'/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m'
	]

libraries = [
	'libPolycore',
	'libPolycode2DPhysics',
	'libpng15',
	'libfreetype',
	'liblibogg',
	'liblibvorbis',
	'liblibvorbisfile',
	'liblua5.1',
	'libphysfs',
	'libz',
	'libPolycode2DPhysics',
	'libPolycode3DPhysics',
	'libPolycodeTUIO',
	'libPolycodeUI',
	'libBox2D',
	'python3.4m',
	'libboost_python3-mt',
	'libMiniCL'
	]

env = Environment(CPPPATH = include_paths,
	LIBPATH = lib_paths,
	CXXFLAGS="-std=c++0x",
	CPPFLAGS=['-Wall', '-g', '-mmacosx-version-min=10.9'],
	LINKFLAGS='-framework Python -framework Cocoa -framework OpenGL -framework OpenAL -framework IOKit -shared',
	CPPDEFINES='BUILD_BINDINGS',
	SHLIBPREFIX='')

game_lib = env.StaticLibrary(target = 'Game', source = Glob('src/*.cpp'), LIBS=libraries)

python_bindings = env.SharedLibrary(target='game.so', source=['src/python/PythonGame.cpp'], LIBS=libraries + game_lib)

Depends(python_bindings, game_lib)

